default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres-login
  password: 12345678
  port: 3000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sistema-courier

test:
  <<: *default
  database: sistema-courier-teste

production:
  <<: *default
  database: sistema-courier-production
  password: <%= ENV['DATABASE_PASSWORD'] %>
